package parser;

enum TokenType {
	EOF, IDENT,INTLIT, STRINGLIT, SKIP, INT, STRING,  PLUS, MINUS, TIMES, DIV, LEQ, LTH, GEQ, GTH, EQ,NEQ, CONCAT, ASSIGN, LET, IN, OPENPAR, CLOSEDPAR,
	OPENSQUAREPAR, CLOSEDSQUAREPAR, BOOL, ELSE, FALSE, FUN, IF, LIST, THEN , TRUE,ARROW, COLON, SEMICOLON, PERCENT, AMPERSAND, AT, COMMA, PIPE, EXTRACTHEAD, EXTRACTTAIL, TILDE, HASH
}
